#
# PHP Farm Docker image
#

# we use Debian as the host OS
FROM philcryer/min-jessie:latest

MAINTAINER Andreas Gohr, andi@splitbrain.org

# the PHP versions to compile
ENV PHP_FARM_VERSIONS "5.3.29 5.4.44 5.5.38 5.6.30 7.0.17 7.1.3"

# make php 5.3 work again
ENV LDFLAGS "-lssl -lcrypto -lstdc++"

# add some build tools
RUN apt-get update && \
    apt-get install -y \
    apache2 \
    apache2-mpm-prefork \
    autoconf \
    build-essential \
    curl \
    debian-archive-keyring \
    debian-keyring \
    git \
    imagemagick \
    lemon \
    libapache2-mod-fcgid \
    libbz2-dev \
    libc-client2007e-dev \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg-dev \
    libkrb5-dev \
    libldap2-dev \
    libltdl-dev \
    libmcrypt-dev \
    libmhash-dev \
    libmysqlclient-dev \
    libpng-dev \
    libpq-dev \
    libsasl2-dev \
    libssl-dev \
    libwebp-dev \
    libxml2-dev \
    libxpm-dev \
    libxslt1-dev \
    pkg-config \
    vim \
    wget

# reconfigure Apache
RUN rm -rf /var/www/*
COPY var-www /var/www/
COPY apache  /etc/apache2/

# install the phpfarm script
RUN git clone https://github.com/fpoirotte/phpfarm.git phpfarm

# add customized configuration
COPY phpfarm /phpfarm/src/

# set path
ENV PATH /phpfarm/inst/bin/:/usr/sbin:/usr/bin:/sbin:/bin

# compile, then delete sources (saves space)
RUN cd /phpfarm/src && ./docker.sh

# expose the ports
EXPOSE 8053 8054 8055 8056 8070 8071

# run it
WORKDIR /var/www
COPY run.sh /run.sh
CMD ["/bin/bash", "/run.sh"]
