#
# PHP Farm Docker image
#

# we use Debian as the host OS
FROM philcryer/min-wheezy:latest

MAINTAINER Andreas Gohr, andi@splitbrain.org

# the PHP versions to compile
ENV PHP_FARM_VERSIONS="5.1.6 5.2.17 5.3.29 5.4.44 5.5.38 5.6.30 7.0.17 7.1.3" \
  \
  # make php 5.3 work again
  LDFLAGS="-lssl -lcrypto -lstdc++" \
  \
  # Packages only needed for PHP build.
  BUILD_DEPS="\
    autoconf \
    build-essential \
    # Flex needed for PHP 5.1 see http://php.net/manual/en/install.unix.php
    flex \
    lemon \
    libbz2-dev \
    libc-client2007e-dev \
    libcurl4-openssl-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg-dev \
    libldap2-dev \
    libltdl-dev \
    libmcrypt-dev \
    libmhash-dev \
    libmysqlclient-dev \
    libpng-dev \
    libpq-dev \
    libsasl2-dev \
    libssl-dev \
    libsslcommon2-dev \
    libt1-dev \
    libwebp-dev \
    libxml2-dev \
    libxpm-dev \
    libxslt1-dev \
    pkg-config \
  " \
  # PHP runtime dependencies.
  RUNTIME_DEPS="\
    curl \
    imagemagick \
    libpq-dev \
    libxslt1-dev \
  " \
  APACHE_DEPS="\
    apache2 \
    apache2-mpm-prefork \
    # Fcgid mod for Apache - not a build dependency library.
    libapache2-mod-fcgid \
  "

# Install packages we need for runtime usage.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    $RUNTIME_DEPS \
    $APACHE_DEPS \
    \
    # Other packages for convenience.
    # git-clone: Fix 'fatal: unable to access https://github.com/...: Problem with the SSL CA cert (path? access rights?)'
    ca-certificates \
    debian-archive-keyring \
    debian-keyring \
    git \
    vim \
    wget && \
    \
    # Clean up apt package lists.
    rm -rf /var/lib/apt/lists/*

# reconfigure Apache
RUN rm -rf /var/www/*
COPY var-www /var/www/
COPY apache  /etc/apache2/

# install the phpfarm script
RUN git clone https://github.com/fpoirotte/phpfarm.git phpfarm

# add customized configuration
COPY phpfarm /phpfarm/src/

# Add path to built PHP executables, for module building and for Apache.
ENV PATH /phpfarm/inst/bin/:/usr/sbin:/usr/bin:/sbin:/bin

# Install packages needed for build.
RUN apt-get update && \
  apt-get install -y --no-install-recommends $BUILD_DEPS && \
  \
  # Build all PHP versions.
  cd /phpfarm/src && \
  ./docker.sh && \
  \
  # Clean up.
  apt-get purge -y $BUILD_DEPS && \
  apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/*

# expose the ports
EXPOSE 8051 8052 8053 8054 8055 8056 8070 8071

# run it
WORKDIR /var/www
COPY run.sh /run.sh
CMD ["/bin/bash", "/run.sh"]
